### ISSUE TITLE
The proxy router isn't handling streaming responses from the server correctly

### ISSUE THREAD

**Issue by mrakgr** [Lumerin-protocol/Morpheus-Lumerin-Node#289] opened 2024-11-21 15:19 UTC
![image](https://github.com/user-attachments/assets/7f5a6e26-7018-47e9-9302-8216c21a2aff)

I recently created the `cognitivecomputations/dolphin-2.9.2-qwen2-72b` model on your testnet chain and when I try using it as a consumer using the desktop UI on my windows PC, I get the above errors on the provider side in the Mor proxy. I think it's trying to convert the response into JSON instead of streaming them back to the consumer. I've already verified that the LiteLLM proxy and the vLLM model servers are streaming the responses correctly, meaning this is an error in the Morpheus proxy router.

**Comment by mrakgr** [comment] 2024-11-21 15:21
It's saying right there that it's trying to decode the response, which it shouldn't be doing.

**Comment by mrakgr** [comment] 2024-11-21 15:26
The commit I am on [is](https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/commit/43214ac082afa468a8364f52b6bcca0ae87a6fd7). I built it using `./build.sh` and am running the proxy router using `make run`.

**Comment by mrakgr** [comment] 2024-11-21 15:27
What I expected is the request would work. What I got is the JSON decoding error in the screenshot.

**Comment by mrakgr** [comment] 2024-11-21 15:31
Here is how the responses look like. I copy pasted this from the middle of the stream. They always start with `data` which isn't valid JSON.

```
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"im"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"_start"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"|"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":">"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"user"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"\n"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":"Do"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":" you"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":" want"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":" to"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
data: {"id":"chatcmpl-cdde9de7-7070-4b63-af49-f11554c2a165","object":"text_completion","created":1732201518,"model":"meta-llama/Llama-3.2-3B","choices":[{"index":0,"text":" leave"}],"usage":{"completion_tokens":0,"prompt_tokens":0,"total_tokens":0}}
```

**Comment by abs2023** [comment] 2024-11-21 15:44
@mrakgr what llm server are you using (Llama.cpp or something else?) 
in your models-config.json what is the url (you can obfuscate the dns or ip address)...but the url should have /v1 as a suffix if it's an openai compatible engine.

**Comment by mrakgr** [comment] 2024-11-21 15:46
```json
{
  "0x5c6a8dd17e4b0d705a8f8b66a2a301db6f1486a0a4034271ff17f856fe7ec508": {
      "modelName": "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://localhost:23330"
  },
  "0x00e503aba8d1faa67c5f232a6ad76626f7d5dd6af61ae36a95dc1ef11e8612a0": {
      "modelName": "meta-llama/Llama-3.2-3B",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://localhost:23330"
  },
  "0xfe4cc20404f223f336f241fa16748b91e8ff1d54141203b0882b637ead9fef79": {
      "modelName": "NousResearch/Hermes-2-Theta-Llama-3-8B",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://localhost:23330"
  },
  "0x27cf27d8d653d548c41619c56b1af3d5c8579d8c5049af18f67e03bb59366837": {
      "modelName": "cognitivecomputations/dolphin-2.9.2-qwen2-72b",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://localhost:23330"
  }
}
```

**Comment by mrakgr** [comment] 2024-11-21 15:47
> what llm server are you using (Llama.cpp or something else?)

The Morpheus proxy server -> LiteLLM proxy server -> vLLM model server.

**Comment by mrakgr** [comment] 2024-11-21 15:49
The LiteLLM proxy server is running on the same node as the Mor proxy router which is why the URL is pointing to localhost.

**Comment by abs2023** [comment] 2024-11-21 15:49
you need to add /v1 to end end of your apiURLs ... you're not querying the same interface that you would if you connected directly.  Please see https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/blob/dev/docs/models-config.json.md for reference. 
`"apiUrl": "http://localhost:23330"` should be `"apiUrl": "http://localhost:23330/v1"

that's at least a first place to start ... as for daisy chaining to LiteLLM proxy and then vLLM model, that is not a design pattern we have looked at.  We are expecting  proxy-router --> llm server

**Comment by mrakgr** [comment] 2024-11-21 15:54
> `"apiUrl": "http://localhost:23330"` should be `"apiUrl": `[http://localhost:23330/v1`](http://localhost:23330/v1%60)

I am going to try doing what you suggest, but I am not expecting much from it. I already ran into this same issue with LiteLLM. It would convert the `/v1` endpoints to regular ones and I'd get 404 errors. I fixed that by adding `/v1` into the `config.yaml` that LiteLLM uses. It looks like this right now, and this does work properly.

```yaml
model_list:
- litellm_params:
    api_base: "http://192.168.69.83:23331/v1"
    api_key: "..."
    model: "openai/nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"
  model_info:
    author: "TODO"
    description: "TODO"
  model_name: "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF"
- litellm_params:
    api_base: "http://192.168.69.74:23331/v1"
    api_key: "..."
    model: "openai/cognitivecomputations/dolphin-2.9.2-qwen2-72b"
  model_info:
    author: "TODO"
    description: "TODO"
  model_name: "cognitivecomputations/dolphin-2.9.2-qwen2-72b"
- litellm_params:
    api_base: "http://192.168.69.76:23331/v1"
    api_key: "..."
    model: "openai/meta-llama/Llama-3.2-3B"
  model_info:
    author: "TODO"
    description: "TODO"
  model_name: "meta-llama/Llama-3.2-3B"
- litellm_params:
    api_base: "http://192.168.69.78:23331/v1"
    api_key: "..."
    model: "openai/NousResearch/Hermes-2-Theta-Llama-3-8B"
  model_info:
    author: "TODO"
    description: "TODO"
  model_name: "NousResearch/Hermes-2-Theta-Llama-3-8B"
```

**Comment by mrakgr** [comment] 2024-11-21 15:55
Let me ask you, the error in the screenshot clearly states that this is a JSON decoding error. Why do you think the error is on our end?

**Comment by abs2023** [comment] 2024-11-21 15:57
> Let me ask you, the error in the screenshot clearly states that this is a JSON decoding error. Why do you think the error is on our end?

Because your design pattern (proxy to proxy to model) is not one that we have tested or encountered, and your configuration does not match the recommended language.  So until you configure it as expected (proxy to llm) with the proper parameters, i can't tell you where the problem is.  You have another unknown component in the middle that may or may not be contributing.  

Frankly, i'd like to see what you get when you set it up like we recommend instead of doing something different and then saying our software is broken.

**Comment by mrakgr** [comment] 2024-11-21 16:02
I added the `/v1` to the urls in the models config file as per your suggestion. Then I tried connecting to the dolphin model from my desktop PC and this is the error that I get. It's the same as before. So that eliminates one possibility. It would take a bit of tinkering, but I'll try bypassing the LiteLLM proxy and routing to the models directly. Stay tuned...

```
2024-11-21T15:56:44.793597297   INFO    started watching events, address 0xb8C55cD613af947E73E262F0d3C54b7211Af16CF
2024-11-21T15:56:44.874445603   DEBUG   =====> calling poll from 99302955 to 99302955
2024-11-21T15:56:55.124324948   DEBUG   =====> calling poll from 99302956 to 99302994
2024-11-21T15:57:05.413795617   DEBUG   =====> calling poll from 99302995 to 99303034
2024-11-21T15:57:15.659616093   DEBUG   =====> calling poll from 99303035 to 99303066
2024-11-21T15:57:25.908721198   DEBUG   =====> calling poll from 99303067 to 99303106
2024-11-21T15:57:36.163529513   DEBUG   =====> calling poll from 99303107 to 99303142
2024-11-21T15:57:44.138749735   ERROR   SRC     Error reading messageEOF        {"SrcAddr": "138.68.131.245:45800"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func4
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/handlers/tcphandlers/tcp.go:31
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/repositories/transport/tcp_server.go:94
2024-11-21T15:57:44.138853704   INFO    SRC     Closing connection      {"SrcAddr": "138.68.131.245:45800"}
2024-11-21T15:57:46.439409294   DEBUG   =====> calling poll from 99303143 to 99303176
2024-11-21T15:57:56.67070762    DEBUG   =====> calling poll from 99303177 to 99303208
2024-11-21T15:58:01.980212148   INFO    SRC     Closing connection      {"SrcAddr": "93.141.21.76:59683"}
2024-11-21T15:58:06.98014127    DEBUG   =====> calling poll from 99303209 to 99303245
2024-11-21T15:58:07.081448024   DEBUG   received open session event, sessionId 0x635ded6666f7cdfaab1dba6ffc0ea562607b4abc1e4d3ac54fd97709211893d0
2024-11-21T15:58:12.270270571   ERROR   SRC     failed to prompt: failed to decode response: invalid character 'd' looking for beginning of value    {"SrcAddr": "93.141.21.76:59686"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*ProxyReceiver).SessionPrompt
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/proxyapi/proxy_receiver.go:108
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).sessionPrompt
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/proxyapi/controller_morrpc.go:133
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).Handle
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/proxyapi/controller_morrpc.go:48
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func4
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/handlers/tcphandlers/tcp.go:35
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/repositories/transport/tcp_server.go:94
2024-11-21T15:58:12.270424089   ERROR   SRC     failed to prompt: failed to decode response: invalid character 'd' looking for beginning of value    {"SrcAddr": "93.141.21.76:59686"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).sessionPrompt
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/proxyapi/controller_morrpc.go:135
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyapi.(*MORRPCController).Handle
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/proxyapi/controller_morrpc.go:48
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func4
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/handlers/tcphandlers/tcp.go:35
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/repositories/transport/tcp_server.go:94
2024-11-21T15:58:12.270526517   ERROR   SRC     Error handling message: failed to prompt: failed to decode response: invalid character 'd' looking for beginning of value
Message: &{1 session.prompt {"signature":"0x95eb7a46012ddbec6841fa00ac38ee3280958bbc9dcb964dc2d8067838d7fd603bbf7823822d92ab29bf462e6c765089a43aec886268455e18c7dbab7833b08901","sessionid":"0x635ded6666f7cdfaab1dba6ffc0ea562607b4abc1e4d3ac54fd97709211893d0","message":"{\"model\":\"\",\"messages\":[{\"role\":\"user\",\"content\":\"Hi.\"}],\"stream\":true}","timestamp":1732204692550}}
        {"SrcAddr": "93.141.21.76:59686"}
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/proxyctl.(*Proxy).run.NewTCPHandler.func4
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/handlers/tcphandlers/tcp.go:45
github.com/MorpheusAIs/Morpheus-Lumerin-Node/proxy-router/internal/repositories/transport.(*TCPServer).startAccepting.func1
        /home/rena/Morpheus-Lumerin-Node-new/proxy-router/internal/repositories/transport/tcp_server.go:94
2024-11-21T15:58:12.270594646   INFO    SRC     Closing connection      {"SrcAddr": "93.141.21.76:59686"}
2024-11-21T15:58:12.760377631   INFO    SRC     Closing connection      {"SrcAddr": "93.141.21.76:59687"}
2024-11-21T15:58:17.166110659   DEBUG   =====> calling poll from 99303246 to 99303282
2024-11-21T15:58:17.261644881   DEBUG   received close session event, sessionId 0x635ded6666f7cdfaab1dba6ffc0ea562607b4abc1e4d3ac54fd97709211893d0
2024-11-21T15:58:27.354136493   DEBUG   =====> calling poll from 99303283 to 99303320
```

**Comment by abs2023** [comment] 2024-11-21 16:03
I don't expect behavior to change until that other proxy is out of the conversation.  Lmk

**Comment by mrakgr** [comment] 2024-11-21 16:06
As per you recommendation I changed the models config so it routes to the vLLM servers directly. I'll try running it.

```
{
  "0x5c6a8dd17e4b0d705a8f8b66a2a301db6f1486a0a4034271ff17f856fe7ec508": {
      "modelName": "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://192.168.69.83:23331/v1"
  },
  "0x27cf27d8d653d548c41619c56b1af3d5c8579d8c5049af18f67e03bb59366837": {
      "modelName": "cognitivecomputations/dolphin-2.9.2-qwen2-72b",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://192.168.69.74:23331/v1"
  },
  "0x00e503aba8d1faa67c5f232a6ad76626f7d5dd6af61ae36a95dc1ef11e8612a0": {
      "modelName": "meta-llama/Llama-3.2-3B",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://192.168.69.76:23331/v1"
  },
  "0xfe4cc20404f223f336f241fa16748b91e8ff1d54141203b0882b637ead9fef79": {
      "modelName": "NousResearch/Hermes-2-Theta-Llama-3-8B",
      "apiType": "openai",
      "apiKey": "...",
      "apiUrl": "http://192.168.69.78:23331/v1"
  }
}
```

**Comment by mrakgr** [comment] 2024-11-21 16:10
I think this error is happening due to it trying to decode the streaming responses into JSON. What do you think?

**Comment by abs2023** [comment] 2024-11-21 17:41
i've checked with my own model (provider and consumer) and the `data: {json}` format is expected and consumed properly when `IsStream: true` is on the chat completions prompt (should be on by default when using the MorpheusUI). You can see an example here when using the API alone to query the proxy-router provider session.  https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/blob/dev/docs/proxy-router-api-direct.md

So, no, it looks like the format is being returned as expected.

**Comment by abs2023** [comment] 2024-11-21 17:42
In your MorpheusUI, on Testnet, see if you can create a session and infer from this model: LMR-Hermes-2-Theta-Llama-3-8B (this is one of our hosted testnet providers/models)

**Comment by mrakgr** [comment] 2024-11-21 17:43
> In your MorpheusUI, on Testnet, see if you can create a session and infer from this model: LMR-Hermes-2-Theta-Llama-3-8B (this is one of our hosted testnet providers/models) ... see what happens when going against a known good provider.

I tried that one and it worked.

**Comment by mrakgr** [comment] 2024-11-21 17:44
> is expected and consumed properly when `IsStream: true` is on the chat completions prompt (should be on by default when using the MorpheusUI). Y

Is it possible that this property is set to false even though the request might have `stream=true`?

**Comment by mrakgr** [comment] 2024-11-21 17:46
Anyway, I'll try compiling the Morpheus proxy router myself tomorrow, and I'll add some print statements to make sure of exactly what is going on.

**Comment by abs2023** [comment] 2024-11-21 17:47
if you're using the MorpheusAI, when you send a prompt, it calls a few of the APIs including ChatCompletion and stream=true...so if all things are configured correctly (and at least on your consumer side confirmed with my model) ... there's still something wrong between your proxy-router and your LLM or the config in between

**Comment by abs2023** [comment] 2024-11-21 17:54
Looking at your models that you've registered ... do you have an api key setup on those models on the llm server? i see they're blanked out here)...but if they're operating in the clear on your private network , i'm wondering if there's something blocking.  

When i try to start a session with any of your models, i get a good session start (good...this means the proxy-router is answering and it has good blockchain connection) ... but on prompt, it fails and closes session saying No Provider as accepting session ... this usually means that something in the models-config.json (either the model is not matching on the blockchain ...not the case here) or it can't route or authenticate to the LLM / Model.  

On our setup, we have the LLM and Proxy Router existing on the same, private network subnet so that the communication between them is "in the clear" and without APIKey required.  Not sure if you've got the ability to setup the same (I do see 192.168 private address on your model servers, so assume it's similar)...but would look at that.

> As per you recommendation I changed the models config so it routes to the vLLM servers directly. I'll try running it.
> 
> ```
> {
>   "0x5c6a8dd17e4b0d705a8f8b66a2a301db6f1486a0a4034271ff17f856fe7ec508": {
>       "modelName": "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
>       "apiType": "openai",
>       "apiKey": "...",
>       "apiUrl": "http://192.168.69.83:23331/v1"
>   },
>   "0x27cf27d8d653d548c41619c56b1af3d5c8579d8c5049af18f67e03bb59366837": {
>       "modelName": "cognitivecomputations/dolphin-2.9.2-qwen2-72b",
>       "apiType": "openai",
>       "apiKey": "...",
>       "apiUrl": "http://192.168.69.74:23331/v1"
>   },
>   "0x00e503aba8d1faa67c5f232a6ad76626f7d5dd6af61ae36a95dc1ef11e8612a0": {
>       "modelName": "meta-llama/Llama-3.2-3B",
>       "apiType": "openai",
>       "apiKey": "...",
>       "apiUrl": "http://192.168.69.76:23331/v1"
>   },
>   "0xfe4cc20404f223f336f241fa16748b91e8ff1d54141203b0882b637ead9fef79": {
>       "modelName": "NousResearch/Hermes-2-Theta-Llama-3-8B",
>       "apiType": "openai",
>       "apiKey": "...",
>       "apiUrl": "http://192.168.69.78:23331/v1"
>   }
> }
> ```

**Comment by abs2023** [comment] 2024-11-21 17:58
2024-11-21T12:54:43.540839	INFO	trying to open session with provider #0 0x61Fc3....722F
2024-11-21T12:54:43.540873	DEBUG	RPC	calling eth_call
2024-11-21T12:54:43.604839	INFO	attempting to initiate session map[amountTransferred:8360000000783737994 bid:0x6e7d50daeb8bce0010c2095494f75eaed67f0a28c08fb059b93c79a96a3b9ea5 directPayment:false duration:26400 endpoint:x.y.z.a:3334 provider:0x61Fc3....722F]
2024-11-21T12:54:55.66713	DEBUG	received open session event, sessionId 0x56494....8140e
![image](https://github.com/user-attachments/assets/8f733a00-ffff-4d7b-8e03-de9a91512355)
2024-11-21T12:56:25.128962	WARN	Connection closed by provider
2024-11-21T12:56:27.298849	DEBUG	received close session event, sessionId 0x56494d7....38140e
2024-11-21T12:56:27.357608	ERROR	error sending prompt: no provider accepting session

**Comment by mrakgr** [comment] 2024-11-21 18:00
Right now, they just ignore it, but I'll configure them properly later.

**Comment by abs2023** [comment] 2024-11-21 18:03
i don't know...both of your llm components (LiteLLM and vLLM) are foreign to me...not sure how they respond or where / how they're hosted which makes this difficult.  The core issue right now is that the prompt isn't making it from the proxy-router to your LLMs ... this can be caused by network, firewall, or misconfig on the models-config file.  Your proxy-router is listening on 64.x.y.z:3334 (and again, i can create session to it which is good) ... but the direct vLLM models are 192.168.x.y:port.  from the proxy router, you *can* `curl 192.168.x.y:port` and get them to respond?

**Comment by mrakgr** [comment] 2024-11-21 18:06
> The core issue right now is that the prompt isn't making it from the proxy-router to your LLMs

No, it's getting to the LLMs from the consumer.  What's happening on the way back is the problem. I have evidence to support this, but it's all on the Ceti <> Morpheus Signal group. What is happening that the request gets to the LLMs, and then the Mor proxy errors out once it gets the response.

**Comment by mrakgr** [comment] 2024-11-21 18:09
> from the proxy router, you _can_ `curl 192.168.x.y:port` and get them to respond?

I have no problem accessing them from the cluster's head node `rena`, but otherwise they are not exposed to the internet.

**Comment by abs2023** [comment] 2024-11-21 19:34
> > The core issue right now is that the prompt isn't making it from the proxy-router to your LLMs
> 
> No, it's getting to the LLMs from the consumer. What's happening on the way back is the problem. I have evidence to support this, but it's all on the Ceti <> Morpheus Signal group. What is happening that the request gets to the LLMs, and then the Mor proxy errors out once it gets the response.

i'm not on that chat... based on what i'm seeing from my consumer proxy/UI is that your proxy-router (Provider) cannot properly talk to the back-end LLM.  The LLM is NEVER supposed to talk directly to the consumer. ... it must run from LLM --> Provider Proxy-router --> NETWORK --> Consumer proxy-router process --> MorpheusUI.  

When i see this error `2024-11-21T12:56:27.357608 ERROR error sending prompt: no provider accepting session` after a good session creation and the provider shuts the session, it means that the provider proxy-router can't see or talk to the LLM server on the back-end. 

I'm trying different scenarios to see if i can replicate your issue on our environment (can't break it so far) ... one thing i noticed ... is that when your proxy starts up the ModelsConfigPath is empty ... where is the models-config.json that you're using ... is it in the same proxy-router folder and is the .env file variable MODELS_CONFIG_PATH correct?

**Comment by abs2023** [comment] 2024-11-21 22:16
So... good news, bad news.....
Good news, i installed LiteLLM on my provider, created the proper yaml file to sit between our proxy and a known running LLM (EC2 instance running llama.cpp) so that i can replicate (some what) your scenario.  
I'm also seeing the error on the provider (so i can recreate the issue with LiteLLM in the middle) 
Bad news ... after running a few tests, i'm not sure that the problem isn't in how LiteLLM takes the input chat json and sends it to the real LLM provider.  

I have a good system when setup as we recommend (proxy-router to llm)...but when introducing the other proxy in the middle, i get the same error.  I see all the right configuration come through the provider to litellm and on to the llm server including the 'stream' = true.  So the data that the provider gets back should be in the same format that it is always used to `data {json}`.  At this point, putting litellm in the middle is not doing us any favors.

**Comment by mrakgr** [comment] 2024-11-22 08:42
> > > The core issue right now is that the prompt isn't making it from the proxy-router to your LLMs
> > 
> > 
> > No, it's getting to the LLMs from the consumer. What's happening on the way back is the problem. I have evidence to support this, but it's all on the Ceti <> Morpheus Signal group. What is happening that the request gets to the LLMs, and then the Mor proxy errors out once it gets the response.
> 
> i'm not on that chat... based on what i'm seeing from my consumer proxy/UI is that your proxy-router (Provider) cannot properly talk to the back-end LLM. The LLM is NEVER supposed to talk directly to the consumer. ... it must run from LLM --> Provider Proxy-router --> NETWORK --> Consumer proxy-router process --> MorpheusUI.
> 
> When i see this error `2024-11-21T12:56:27.357608 ERROR error sending prompt: no provider accepting session` after a good session creation and the provider shuts the session, it means that the provider proxy-router can't see or talk to the LLM server on the back-end.

Yeah, it going through the Mor proxy router. That is what I've been testing.

> I'm trying different scenarios to see if i can replicate your issue on our environment (can't break it so far) ... one thing i noticed ... is that when your proxy starts up the ModelsConfigPath is empty ... where is the models-config.json that you're using ... is it in the same proxy-router folder and is the .env file variable MODELS_CONFIG_PATH correct?

Yes, but I don't have anything in the models config path, so it's defaulting to the same dir.

**Comment by mrakgr** [comment] 2024-11-22 09:13
![image](https://github.com/user-attachments/assets/6a96f461-e5cc-4c5c-a590-09c62f1ada37)

Right now, I am testing and the message isn't getting to the model server it seems. There might be something to what you said. I'll try enabling LiteLLM again.

**Comment by mrakgr** [comment] 2024-11-22 09:16
Oh, nevermind, it opened the session. I just didn't send any request.

**Comment by mrakgr** [comment] 2024-11-22 09:20
![image](https://github.com/user-attachments/assets/b153c781-7d35-4089-aa3e-e527bf79b59a)

This part where it is marshalling JSON seems suspicious. It probably shouldn't be doing that.

**Comment by mrakgr** [comment] 2024-11-22 09:27
![image](https://github.com/user-attachments/assets/969d4fc7-6ea4-4500-ba5d-6db85600d150)

Spoke too soon. None of the lamda body errors trigger, meaning the error is in the `adapter.Prompt` itself.

**Comment by mrakgr** [comment] 2024-11-22 09:36
![image](https://github.com/user-attachments/assets/741e3231-88d0-4586-b997-b9817eeece02)

What I am doing here is pretty basic, tracing down the error. Maybe we'll have something to discuss by the end of it. I think at this point I can just go to the end point instead...

**Comment by mrakgr** [comment] 2024-11-22 09:46
Actually, what I was looking at initially was the final function where the error occurred. But because it's behind a bunch of indirections I'll have to use a debugger to trace into it. Now how do I configure this project to do that?

**Comment by mrakgr** [comment] 2024-11-22 09:50
![image](https://github.com/user-attachments/assets/81fe8d0a-e74d-4cf4-9e7f-8b82143fcf7d)
Got the debugger setup. Now let's see...

**Comment by mrakgr** [comment] 2024-11-22 09:54
![image](https://github.com/user-attachments/assets/d8bf4b95-c458-44e5-a7a2-8ea0bf7711e0)
What's weird here is that there are a bunch of errors in the terminal, but the actual error returned from this function is nil.

**Comment by mrakgr** [comment] 2024-11-22 09:59
![image](https://github.com/user-attachments/assets/17a14eb1-6ee2-4d36-9760-91429dc3fc4a)
It's getting back a stream here. So far so good...

**Comment by mrakgr** [comment] 2024-11-22 09:59
![image](https://github.com/user-attachments/assets/16ce0ed3-8857-4b37-bef2-b89063a049bf)
Ah, damn, it skipped over it. It isn't actually reading the stream!

**Comment by mrakgr** [comment] 2024-11-22 10:03
What is happening is that `contentType` is `"text/event-stream; charset=utf-8"`, but the `CONTENT_TYPE_EVENT_STREAM` is `"text/event-stream"` so the equality check fails. That is the error we're looking for 100%.

**Comment by abs2023** [comment] 2024-11-22 13:49
> What is happening is that `contentType` is `"text/event-stream; charset=utf-8"`, but the `CONTENT_TYPE_EVENT_STREAM` is `"text/event-stream"` so the equality check fails. That is the error we're looking for 100%.

Good morning ... thanks for digging into this, nice work....if i understand correctly, someone wants to make sure that the contentType passed and received is the same ... and because there's an extra charset condition, something fails.  Now, i'm not a developer .. which component is failing the check? is in the proxy-router discarding the response because the response contentType doesn't match what is returned from LiteLLM? (just want to be clear so i can point our folks at this quickly)

**Comment by abs2023** [comment] 2024-11-22 17:11
@mrakgr ... Thank you for your drive to find the root cause.  We were able to recreate the issue and also found another one that would likely affect message transmission in the chain.  Currently working on a fix and should be in TEST shortly.   will repost here when it's ready for you.  Thank you again.

**Comment by abs2023** [comment] 2024-11-22 21:25
Fix implemented and rolled in to TEST branch (replaces STG branch ... to reduce confusion) ... please update and see if that fixes your issue.  Also updated TEST-Release (build should be done soon) for the UI portion 
https://github.com/Lumerin-protocol/Morpheus-Lumerin-Node/tree/test (TESTNET code update for community testing)

**Closed by abs2023** 2024-11-22 21:25 UTC
